### ISSUE TITLE
Would you like to join the 'firefox-theme' organization?

### ISSUE THREAD

**Issue by eronh** [gt-rios/firefox-syntax#4]
Hello @gt-rios 

I am also a fan of the Firefox' developer tools colors, and I have seen that you have done a great job on your Atom version.

I have created a Visual Studio Code version and just submitted one for Sublime Text (that still needs to be approved by Package Control).

Recently, I turned the theme into an organization, as I planned to distribute to other editors.

Would you like to join the [Firefox Theme organization](https://github.com/firefox-theme)?
It would require you to transfer the ownership of your repository.

Let me know if you're interested :)
Thanks for your time!

**Comment by dindrala** [comment]
@heronsilva Any plans on building Firefox developer tool colors for Brackets editor? Fingers crossed!

**Comment by gt-rios** [comment]
Hi @heronsilva. That's a good idea, I'll join but give me about a week to tidy up the repo before the transfer because it's currently undergoing a major rewrite.

**Comment by eronh** [comment]
Hi @dindrala 
That would be cool! Honestly, I haven't used Brackets in a long time, but still I would give it a try :)

**Comment by eronh** [comment]
@gt-rios 
No problem, take all the time you need.
I'm glad you're interested :)

**Comment by dindrala** [comment]
@heronsilva Sounds good! Ill check your page for updates :)
